name: xmlrpc
author: Kirill Vergun <pub.dartlang.org@o-nix.me>
version: 1.0.0
description: Useful helper classes for the XML-RPC parsing.
documentation: http://o-nix.me/dart-xmlrpc/xmlrpc.html
homepage: https://github.com/o-nix/dart-xmlrpc

dependencies:
  xml: '>=0.9.5'
  intl: any
  crypto: any

dev_dependencies:
  unittest: any

environment:
  sdk: '>=1.0.0'